/**
 * API Configuration and Endpoints
 * Consolidated from api.ts and apiEndpoints.ts
 */

import { API_CONFIG, API_ENDPOINTS } from "../config";

// API Base Configuration
export const API_BASE_URL =
  "https://fb4c-109-147-151-140.ngrok-free.app/api/v1";

// Authentication endpoints
export const AUTH_ENDPOINTS = {
  LOGIN: API_ENDPOINTS.AUTH_LOGIN,
  REGISTER: API_ENDPOINTS.AUTH_REGISTER,
  REFRESH_TOKEN: API_ENDPOINTS.AUTH_REFRESH_TOKEN,
  FORGOT_PASSWORD: API_ENDPOINTS.AUTH_FORGOT_PASSWORD,
  RESET_PASSWORD: API_ENDPOINTS.AUTH_RESET_PASSWORD,
};

// Property-related endpoints
export const PROPERTY_ENDPOINTS = {
  SEARCH: API_ENDPOINTS.PROPERTY_SEARCH,
  FEATURED: API_ENDPOINTS.PROPERTY_FEATURED,
  NEARBY: API_ENDPOINTS.PROPERTY_NEARBY,
  DETAILS: (id: string) => `${API_ENDPOINTS.PROPERTY_DETAILS}/${id}`,
  CALENDAR: (id: string) =>
    `${API_ENDPOINTS.PROPERTY_DETAILS}/${id}${API_ENDPOINTS.PROPERTY_CALENDAR}`,
  UNITS: (id: string) =>
    `${API_ENDPOINTS.PROPERTY_DETAILS}/${id}${API_ENDPOINTS.PROPERTY_UNITS}`,
  UNIT_DETAILS: (propertyId: string, unitId: string) =>
    `${API_ENDPOINTS.PROPERTY_DETAILS}/${propertyId}${API_ENDPOINTS.PROPERTY_UNITS}/${unitId}`,
  REVIEWS: (id: string) =>
    `${API_ENDPOINTS.PROPERTY_DETAILS}/${id}${API_ENDPOINTS.PROPERTY_REVIEWS}`,
  AVAILABILITY: (id: string) =>
    `${API_ENDPOINTS.PROPERTY_DETAILS}/${id}${API_ENDPOINTS.PROPERTY_AVAILABILITY}`,
};

// Search-related endpoints
export const SEARCH_ENDPOINTS = {
  GENERAL: API_ENDPOINTS.SEARCH_GENERAL,
  SUGGESTIONS: API_ENDPOINTS.SEARCH_SUGGESTIONS,
  NEARBY: API_ENDPOINTS.SEARCH_NEARBY,
  TRENDING: API_ENDPOINTS.SEARCH_TRENDING,
};

// User/traveler endpoints
export const USER_ENDPOINTS = {
  PROFILE: API_ENDPOINTS.USER_PROFILE,
  UPDATE_PROFILE: API_ENDPOINTS.USER_UPDATE_PROFILE,
  BOOKINGS: API_ENDPOINTS.USER_BOOKINGS,
  BOOKING: (id: string) => `${API_ENDPOINTS.USER_BOOKINGS}/${id}`,
  FAVORITES: API_ENDPOINTS.USER_FAVORITES,
  MESSAGES: API_ENDPOINTS.USER_MESSAGES,
  MESSAGES_CONVERSATION: (id: string) => `${API_ENDPOINTS.USER_MESSAGES}/${id}`,
};

// Host endpoints
export const HOST_ENDPOINTS = {
  DASHBOARD: API_ENDPOINTS.HOST_DASHBOARD,
  PROPERTIES: API_ENDPOINTS.HOST_PROPERTIES,
  PROPERTY: (id: string) => `${API_ENDPOINTS.HOST_PROPERTIES}/${id}`,
  EARNINGS: API_ENDPOINTS.HOST_EARNINGS,
  RESERVATIONS: API_ENDPOINTS.HOST_RESERVATIONS,
  RESERVATION: (id: string) => `${API_ENDPOINTS.HOST_RESERVATIONS}/${id}`,
  MESSAGES: API_ENDPOINTS.HOST_MESSAGES,
  MESSAGES_CONVERSATION: (id: string) => `${API_ENDPOINTS.HOST_MESSAGES}/${id}`,
  SETTINGS: API_ENDPOINTS.HOST_SETTINGS,
};

// Booking endpoints
export const BOOKING_ENDPOINTS = {
  CREATE: API_ENDPOINTS.BOOKING_CREATE,
  USER_BOOKINGS: API_ENDPOINTS.BOOKING_USER_BOOKINGS,
  DETAILS: (id: string) => `${API_ENDPOINTS.BOOKING_CREATE}/${id}`,
  CANCEL: (id: string) => `${API_ENDPOINTS.BOOKING_CREATE}/${id}/cancel`,
};

// Legacy consolidated export for backwards compatibility
export const ENDPOINTS = {
  AUTH: AUTH_ENDPOINTS,
  HOST: HOST_ENDPOINTS,
  USER: USER_ENDPOINTS,
  PROPERTIES: PROPERTY_ENDPOINTS,
  SEARCH: SEARCH_ENDPOINTS,
  BOOKING: BOOKING_ENDPOINTS,
};
