name: Android Submit to Play Store

on:
  workflow_dispatch: {} # Manual trigger only

jobs:
  get_latest_build:
    name: Get Latest Android Build
    type: get-build
    params:
      platform: android
      profile: production

  submit_to_play_store:
    name: Submit to Google Play Store
    type: submit
    environment: production
    needs: [get_latest_build]
    params:
      platform: android
      profile: production
      build_id: ${{ needs.get_latest_build.outputs.build_id }}
    env:
      EXPO_DEBUG: "1"