// /**
//  * Mock data for development
//  */

// import { PropertyType } from "../../types/property";

// export const mockProperties: PropertyType[] = [
//   {
//     id: "1",
//     title: "Luxury Beachfront Villa",
//     description:
//       "Stunning beachfront villa with panoramic ocean views. This spacious property features an infinity pool, private access to the beach, and luxurious furnishings throughout.",
//     images: [
//       "https://images.unsplash.com/photo-1577495508048-b635879837f1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1565623833408-d77e39b88af6?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//     ],
//     price: 350,
//     location: "Malibu, California",
//     rating: 4.97,
//     reviewCount: 128,
//     isSuperHost: true,
//     isWishlisted: false,
//     amenities: [
//       "Pool",
//       "Beachfront",
//       "Wifi",
//       "Kitchen",
//       "Free parking",
//       "Air conditioning",
//     ],
//     bedrooms: 4,
//     beds: 5,
//     bathrooms: 3,
//     maxGuests: 8,
//     coordinates: {
//       latitude: 34.025922,
//       longitude: -118.779757,
//     },
//     hostId: "host-1",
//     hostName: "Sarah Johnson",
//     hostImage: "https://randomuser.me/api/portraits/women/44.jpg",
//   },
//   {
//     id: "2",
//     title: "Modern Downtown Loft",
//     description:
//       "Stylish loft in the heart of the city with floor-to-ceiling windows offering spectacular city views. Recently renovated with modern amenities and designer furnishings.",
//     images: [
//       "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
//       "https://images.unsplash.com/photo-1511389026070-a14ae610a1be?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80",
//     ],
//     price: 175,
//     location: "Downtown, New York",
//     rating: 4.85,
//     reviewCount: 94,
//     isSuperHost: false,
//     isWishlisted: true,
//     amenities: [
//       "Wifi",
//       "Kitchen",
//       "Gym access",
//       "Washer/Dryer",
//       "Air conditioning",
//     ],
//     bedrooms: 1,
//     beds: 1,
//     bathrooms: 1,
//     maxGuests: 2,
//     coordinates: {
//       latitude: 40.7128,
//       longitude: -74.006,
//     },
//     hostId: "host-2",
//     hostName: "Michael Chen",
//     hostImage: "https://randomuser.me/api/portraits/men/32.jpg",
//   },
//   {
//     id: "3",
//     title: "Cozy Mountain Cabin",
//     description:
//       "Rustic cabin surrounded by pine trees with stunning mountain views. Features a wood-burning fireplace, hot tub on the deck, and hiking trails right outside your door.",
//     images: [
//       "https://images.unsplash.com/photo-1482192505345-5655af888cc4?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1595274459742-4a5387a7016c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//     ],
//     price: 225,
//     location: "Aspen, Colorado",
//     rating: 4.92,
//     reviewCount: 67,
//     isSuperHost: true,
//     isWishlisted: false,
//     amenities: [
//       "Fireplace",
//       "Hot tub",
//       "Wifi",
//       "Kitchen",
//       "Free parking",
//       "Mountain view",
//     ],
//     bedrooms: 2,
//     beds: 3,
//     bathrooms: 2,
//     maxGuests: 6,
//     coordinates: {
//       latitude: 39.1911,
//       longitude: -106.8175,
//     },
//     hostId: "host-3",
//     hostName: "Emily Rodriguez",
//     hostImage: "https://randomuser.me/api/portraits/women/28.jpg",
//   },
//   {
//     id: "4",
//     title: "Historic City Apartment",
//     description:
//       "Charming apartment in a historic building with original features and modern updates. Located in a vibrant neighborhood with cafes, shops, and restaurants just steps away.",
//     images: [
//       "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1351&q=80",
//     ],
//     price: 135,
//     location: "Boston, Massachusetts",
//     rating: 4.8,
//     reviewCount: 54,
//     isSuperHost: false,
//     isWishlisted: false,
//     amenities: [
//       "Wifi",
//       "Kitchen",
//       "Washer/Dryer",
//       "Air conditioning",
//       "Heating",
//     ],
//     bedrooms: 1,
//     beds: 1,
//     bathrooms: 1,
//     maxGuests: 2,
//     coordinates: {
//       latitude: 42.3601,
//       longitude: -71.0589,
//     },
//     hostId: "host-4",
//     hostName: "David Wilson",
//     hostImage: "https://randomuser.me/api/portraits/men/46.jpg",
//   },
//   {
//     id: "5",
//     title: "Tropical Paradise Villa",
//     description:
//       "Experience the ultimate tropical getaway in this luxurious villa with a private pool. Surrounded by lush gardens with exotic flowers and just a short walk to pristine beaches.",
//     images: [
//       "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1267&q=80",
//     ],
//     price: 280,
//     location: "Bali, Indonesia",
//     rating: 4.95,
//     reviewCount: 112,
//     isSuperHost: true,
//     isWishlisted: true,
//     amenities: [
//       "Pool",
//       "Near beach",
//       "Air conditioning",
//       "Wifi",
//       "Kitchen",
//       "Garden",
//     ],
//     bedrooms: 3,
//     beds: 4,
//     bathrooms: 3,
//     maxGuests: 6,
//     coordinates: {
//       latitude: -8.3405,
//       longitude: 115.092,
//     },
//     hostId: "host-5",
//     hostName: "Ayu Dewi",
//     hostImage: "https://randomuser.me/api/portraits/women/62.jpg",
//   },
//   {
//     id: "6",
//     title: "Stylish Urban Condo",
//     description:
//       "Contemporary condo in a secure building with concierge service. Features an open floor plan, premium finishes, and a balcony with city views.",
//     images: [
//       "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//       "https://images.unsplash.com/photo-1484101403633-562f891dc89a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1353&q=80",
//       "https://images.unsplash.com/photo-1556912173-3bb406ef7e77?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80",
//     ],
//     price: 195,
//     location: "Chicago, Illinois",
//     rating: 4.87,
//     reviewCount: 78,
//     isSuperHost: false,
//     isWishlisted: false,
//     amenities: [
//       "Wifi",
//       "Gym",
//       "Parking",
//       "Washer/Dryer",
//       "Air conditioning",
//       "Doorman",
//     ],
//     bedrooms: 1,
//     beds: 1,
//     bathrooms: 1,
//     maxGuests: 2,
//     coordinates: {
//       latitude: 41.8781,
//       longitude: -87.6298,
//     },
//     hostId: "host-6",
//     hostName: "James Thompson",
//     hostImage: "https://randomuser.me/api/portraits/men/22.jpg",
//   },
// ];

// export const mockBookings = [
//   {
//     id: "booking-1",
//     propertyId: "1",
//     property: mockProperties[0],
//     startDate: "2025-05-15",
//     endDate: "2025-05-20",
//     guestCount: 4,
//     totalPrice: 1750,
//     status: "confirmed",
//     createdAt: "2025-02-10T14:30:00Z",
//   },
//   {
//     id: "booking-2",
//     propertyId: "3",
//     property: mockProperties[2],
//     startDate: "2025-06-08",
//     endDate: "2025-06-12",
//     guestCount: 2,
//     totalPrice: 900,
//     status: "pending",
//     createdAt: "2025-04-05T09:15:00Z",
//   },
//   {
//     id: "booking-3",
//     propertyId: "5",
//     property: mockProperties[4],
//     startDate: "2025-05-01",
//     endDate: "2025-05-07",
//     guestCount: 3,
//     totalPrice: 1960,
//     status: "completed",
//     createdAt: "2025-01-20T11:45:00Z",
//   },
// ];

// export const mockConversations = [
//   {
//     id: "conv-1",
//     propertyId: "1",
//     property: {
//       title: mockProperties[0].title,
//       image: mockProperties[0].images[0],
//     },
//     hostId: mockProperties[0].hostId,
//     hostName: mockProperties[0].hostName,
//     hostImage: mockProperties[0].hostImage,
//     lastMessage: {
//       text: "I look forward to welcoming you next week! Let me know if you have any questions before your arrival.",
//       sentAt: "2025-04-17T14:30:00Z",
//       sentByHost: true,
//       read: true,
//     },
//     unreadCount: 0,
//   },
//   {
//     id: "conv-2",
//     propertyId: "3",
//     property: {
//       title: mockProperties[2].title,
//       image: mockProperties[2].images[0],
//     },
//     hostId: mockProperties[2].hostId,
//     hostName: mockProperties[2].hostName,
//     hostImage: mockProperties[2].hostImage,
//     lastMessage: {
//       text: "Is late check-in possible? My flight arrives at 11pm.",
//       sentAt: "2025-04-17T18:15:00Z",
//       sentByHost: false,
//       read: false,
//     },
//     unreadCount: 2,
//   },
//   {
//     id: "conv-3",
//     propertyId: "5",
//     property: {
//       title: mockProperties[4].title,
//       image: mockProperties[4].images[0],
//     },
//     hostId: mockProperties[4].hostId,
//     hostName: mockProperties[4].hostName,
//     hostImage: mockProperties[4].hostImage,
//     lastMessage: {
//       text: "Thank you for staying with us! Hope to see you again soon.",
//       sentAt: "2025-04-10T09:45:00Z",
//       sentByHost: true,
//       read: true,
//     },
//     unreadCount: 0,
//   },
// ];

// export const mockUser = {
//   id: "user-1",
//   name: "Alex Morgan",
//   email: "alex.morgan@example.com",
//   phone: "+1 555-123-4567",
//   image: "https://randomuser.me/api/portraits/women/75.jpg",
//   joinedDate: "2023-06-15T00:00:00Z",
//   isVerified: true,
//   wishlist: [mockProperties[1].id, mockProperties[4].id],
// };
