name: iOS Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci

      - name: Set up Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: cd ios && pod install

      - name: Decode and install certificate
        run: |
          echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$IOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings
        env:
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}

      - name: Decode and install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$IOS_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
        env:
          IOS_PROFILE_BASE64: ${{ secrets.IOS_PROFILE_BASE64 }}

      - name: Debug List installed provisioning profiles
        run: |
          echo "Listing provisioning profiles:"
          ls -lh ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "----"
          for f in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision; do
            echo "Profile: $f"
            grep -a -A 1 -E 'UUID|Name|application-identifier|TeamIdentifier' "$f" || true
            echo "----"
          done

      - name: Build iOS app (archive)
        run: |
          cd ios
          xcodebuild archive \
            -workspace hoy.xcworkspace \
            -scheme hoy \
            -destination 'generic/platform=iOS' \
            -archivePath ${{ github.workspace }}/build.xcarchive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="76e99446-33c9-4298-b595-7e31ba3d8970" \
            CODE_SIGN_IDENTITY="Apple Development" \
            DEVELOPMENT_TEAM=L9PA57Q5W8
