name: Sync to Public Repo

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'package.json'
      - 'app.json'

permissions:
  contents: read

jobs:
  sync-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Sync to public repo
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          # Clone public repo
          git clone https://$PUBLIC_REPO_TOKEN@github.com/yahya-m2000/app-hoybnb.git public-repo
          cd public-repo
          
          # Copy and sanitize README
          cp ../README.md ./README.md
          
          # Get current version from package.json
          VERSION=$(node -p "require('../package.json').version")
          
          # Create/update tag if it doesn't exist
          if ! git rev-parse "v$VERSION" >/dev/null 2>&1; then
            git tag "v$VERSION"
          fi
          
          # Commit and push changes
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Sync from private repo: v$VERSION"
          git push origin main --tags